# books
- id: isbn-13:9788871926247
  title: Evoluzione. Modelli e processi
  authors:
  - Marco Ferraguti
  - Carla Castellacci
  - Giuliana Allegrucci
  - Giorgio Binelli
  - Maurizio Casiraghi
  - Roberta Cimmaruta
  - Giuseppe Fusco
  - Mauro Mandrioli
  - Lino Ometto
  - Marco Passamonti
  publisher: Pearson Education
  date: '2011-03-16'
  link: https://books.google.it/books/about/Evoluzione_Modelli_e_processi.html?id=fz9RYgEACAAJ&redir_esc=y
  image: images/article_thumbnails/thumb.evoluzione_libro.jpg

- id: https://doi.org/10.1007/978-1-0716-4583-3
  title: 'Insect Genomics: Methods and Protocols'
  authors:
  - Mariangela Bonizzoni
  - Lino Ometto (Eds.)
  publisher: Humana - Springer Nature
  date: '2025-08-20'
  image: images/article_thumbnails/thumb.insectgenomics.jpg

# articles
- id: https://doi.org/10.1093/molbev/msaf132
  title: 'Footprints of worldwide adaptation in structured populations of <i>D. melanogaster</i> through the expanded DEST 2.0 genomic resource'
  image: images/article_thumbnails/thumb.DEST2.png

- id: doi:10.1111/mec.70001
  title: 'Biodiversity genomics research practices require harmonising to meet stakeholder needs in conservation'
  image: images/article_thumbnails/thumb.stake.jpg

- id: doi:10.1371/journal.pone.0308901
  title: 'A framework to identify opportunities to address socioscientific issues in the elementary school curricula: A case study from England, Italy, and Portugal'
  image: images/article_thumbnails/thumb.SSI.png

- id: doi:10.1007/s12600-024-01205-y
  title: 'An initial investigation into the genetic diversity, phylogenetic relationships, and population structure of the Olive Psyllid <i>Euphyllura olivina</i> in Tunisia'
  image: images/article_thumbnails/thumb.olivina.jpg

- id: doi:10.1007/s12600-024-01208-9
  title: 'Genetic diversity in the tomato leafminer <i>Tuta absoluta</i> (Meyrick) in Tunisia'
  image: images/article_thumbnails/thumb.tuta.jpg

- id: doi:10.1038/s44185-024-00054-6
  title: 'The European Reference Genome Atlas: piloting a decentralised approach to equitable biodiversity genomics'
  image: images/article_thumbnails/thumb.erga.jpg

- id: doi:10.1186/s12052-024-00203-2
  title: 'Evolution content in school textbooks: data from eight European countries'
  image: images/article_thumbnails/thumb.evotexts.png

- id: doi:10.1093/molbev/msad193
  title: 'Relaxation of natural selection in the evolution of the giant lungfish genomes'
  image: images/article_thumbnails/thumb.lungfish.jpg

- id: doi:10.1038/s41437-022-00564-8
  title: 'Selection-driven adaptation to the extreme Antarctic environment in the Emperor penguin'
  image: images/article_thumbnails/thumb.penguin.png

- id: doi:10.3390/insects13070603
  title: 'The impact of fast radiation on the phylogeny of <i>Bactrocera</i> fruit flies as revealed by multiple evolutionary models and mutation rate-calibrated clock'
  image: images/article_thumbnails/thumb.bactrocera.png

- id: http:http://www.bulletinofinsectology.org/pdfarticles/vol74-2021-253-257luchetti.pdf
  title: 'The complete mitogenome of the European mantis, <i>Mantis religiosa</i>, from Italy: implications for the origin of North American mantis population'
  authors:
  - Andrea Luchetti
  - Lino Ometto
  - Omar Rota-Stabelli
  publisher: Bulletin of Insectology
  date: '2021-11-01'
  image: images/article_thumbnails/thumb.mantis.png
  link: http://www.bulletinofinsectology.org/pdfarticles/vol74-2021-253-257luchetti.pdf

- id: doi:10.1093/gbe/evab170
  title: 'Phylogenomics of Opsin genes in Diptera reveals lineage-specific events and contrasting evolutionary dynamics in <i>Anopheles</i> and <i>Drosophila</i>'
  image: images/article_thumbnails/thumb.diptera_rh.jpg

- id: doi:10.1186/s12915-021-01148-4
  title: 'Viviparity and habitat restrictions may influence the evolution of male reproductive genes in tsetse fly (<i>Glossina</i>) species'
  image: images/article_thumbnails/thumb.glossinamags.png

- id: doi:10.1093/molbev/msab259
  title: '<i>Drosophila</i> Evolution over Space and Time (DEST): A new population genomics resource'
  image: images/article_thumbnails/thumb.droso_dest.jpg

- id: doi:10.1093/ve/veab031
  title: 'The discovery, distribution, and diversity of DNA viruses associated with <i>Drosophila melanogaster</i> in Europe'
  image: images/article_thumbnails/thumb.droso_virus.jpg

- id: doi:10.1016/j.ibmb.2020.103474
  title: 'Linking omics and ecology to dissect interactions between the apple proliferation phytoplasma and its psyllid vector <i>Cacopsylla melanoneura</i>'
  image: images/article_thumbnails/thumb.cacopsylla.jpg

- id: doi:10.1007/s10340-019-01172-y
  title: 'Distinct genotypes and phenotypes in European and American strains of <i>Drosophila suzukii</i>: implications for biology and management of an invasive organism'
  image: images/article_thumbnails/thumb.suz_ITvsUSA.jpg

- id: doi:10.1371/journal.pntd.0007919
  title: 'Polymorphism analyses and protein modelling inform on functional specialization of <i>Piwi</i> clade genes in the arboviral vector <i>Aedes albopictus</i>'
  image: images/article_thumbnails/thumb.mosq_piwi.jpg

- id: doi:10.1038/s41467-019-12175-9
  title: 'A chromosome-level genome assembly of <i>Cydia pomonella</i> provides insights into chemical ecology and insecticide resistance'
  image: images/article_thumbnails/thumb.pomonella.jpg

- id: doi:10.1186/s13059-019-1768-2
  title: 'Comparative genomic analysis of six <i>Glossina</i> genomes, vectors of African trypanosomes'
  image: images/article_thumbnails/thumb.glossina.jpg

- id: doi:10.1007/s10340-018-0985-x
  title: 'Large-scale spatial dynamics of <i>Drosophila suzukii</i> in Trentino, Italy'
  image: images/article_thumbnails/thumb.suz_trentino.jpg

- id: doi:10.1073/pnas.1707279114
  title: 'Survival and divergence in a small group: The extraordinary genomic history of the endangered Apennine brown bear stragglers'
  image: images/article_thumbnails/thumb.orso.jpg

- id: doi:10.1186/s12863-017-0558-7
  title: 'Genetic variability in Italian populations of <i>Drosophila suzukii</i>'
  image: images/article_thumbnails/thumb.suz_ita.png

- id: doi:10.1002/ece3.3449
  title: 'Genome comparisons indicate recent transfer of <i>w</i>Ri-like <i>Wolbachia</i> between sister species <i>Drosophila suzukii</i> and <i>D. subpulchrella</i>'
  image: images/article_thumbnails/thumb.droso_wRi.jpg

- id: doi:10.1186/s12864-017-3903-3
  title: 'Comparative genomics shows that viral integrations are abundant and express piRNAs in the arboviral vectors <i>Aedes aegypti</i> and <i>Aedes albopictus</i>'
  image: images/article_thumbnails/thumb.mosq_nirvs.gif

- id: doi:10.1534/g3.116.036467
  title: 'Evolutionary insights into taste perception of the invasive pest <i>Drosophila suzukii</i>'
  image: images/article_thumbnails/thumb.suz_taste.png

- id: doi:10.1093/gbe/evw160
  title: 'The evolution of olfactory gene families in <i>Drosophila</i> and the genomic basis of chemical-ecological adaptation in <i>Drosophila suzukii</i>'
  image: images/article_thumbnails/thumb.suz_orgr.jpeg

- id: doi:10.1007/s10340-016-0753-8
  title: 'Multiple lines of evidence for reproductive winter diapause in the invasive pest <i>Drosophila suzukii</i>: useful clues for control strategies'
  image: images/article_thumbnails/thumb.suz_pest.png

- id: doi:10.1111/2041-210X.12453
  title: 'Extracting spatio-temporal patterns in animal trajectories: an ecological application of sequence analysis methods'
  image: images/article_thumbnails/thumb.capriolo.png

- id: doi:10.1371/journal.pone.0125199
  title: 'Demographic history, population structure, and local adaptation in Alpine populations of <i>Cardamine impatiens</i> and <i>Cardamine resedifolia</i>'
  image: images/article_thumbnails/thumb.cardamine.png

- id: doi:10.1093/molbev/msu075
  title: 'Interkingdom transfer of the acne-causing agent, <i>Propionibacterium acnes</i>, from human to grapevine'
  image: images/article_thumbnails/thumb.acne.jpg

- id: doi:10.1093/gbe/evt034
  title: 'linking genomics and ecology to investigate the complex evolution of an invasive <i>Drosophila</i> pest'
  image: images/article_thumbnails/thumb.suz_genome.png

- id: doi:10.1111/nph.12163
  title: 'Spatiotemporal reconstruction of the <i>Aquilegia</i> rapid radiation through next-generation sequencing of rapidly evolving cpDNA regions'
  image: images/article_thumbnails/thumb.aquilegia.jpg

- id: doi:10.1371/journal.pone.0056629.s003
  title: 'Selective sweep in the <i>Flotillin-2</i> region of European <i>Drosophila melanogaster</i>'
  authors:
  - Annegret Werzner
  - Pavlos Pavlidis
  - Lino Ometto
  - Wolfgang Stephan
  - Stefan Laurent
  publisher: PLOS ONE
  date: '2013-02-21'
  link: https://doi.org/10.1371/journal.pone.0056629
  image: images/article_thumbnails/thumb.droso_flotillin.png

- id: doi:10.1093/molbev/mss234
  title: 'Evolution at two levels in fire ants: The relationship between patterns of gene expression and protein sequence evolution'
  image: images/article_thumbnails/thumb.ants_2levels.jpeg

- id: doi:10.1186/1471-2148-12-7
  title: 'Rates of evolution in stress-related genes are associated with habitat preference in two <i>Cardamine</i> lineages'
  image: images/article_thumbnails/thumb.cardamine_cold.jpg

- id: doi:10.1111/j.1365-294X.2012.05544.x
  title: 'Disruption of gene expression in hybrids of the fire ants <i>Solenopsis invicta</i> and <i>Solenopsis richteri</i>'
  authors:
  - Lino Ometto
  - Kenneth G. Ross
  - DeWayne Shoemaker
  - Laurent Keller
  image: images/article_thumbnails/thumb.ants_hybr.png

- id: doi:10.1073/pnas.1104825108
  title: 'Relaxed selection is a precursor to the evolution of phenotypic plasticity'
  image: images/article_thumbnails/thumb.ants_relax.png

- id: doi:10.1093/molbev/msq322
  title: 'Evolution of gene expression in fire ants: The effects of developmental stage, caste, and species'
  authors:
  - Lino Ometto
  - DeWayne Shoemaker
  - Kenneth G. Ross
  - Laurent Keller
  image: images/article_thumbnails/thumb.ants_genex.png

- id: doi:10.1098/rsbl.2006.0521
  title: 'Contrasting patterns of sequence divergence and base composition between <i>Drosophila</i> introns and intergenic regions'
  image: images/article_thumbnails/thumb.droso_interintron.png

- id: doi:10.1093/molbev/msi207
  title: 'Inferring the effects of demography and selection on <i>Drosophila melanogaster</i> populations from a chromosome-wide scan of DNA variation'
  image: images/article_thumbnails/thumb.droso_euro.png

- id: doi:10.1534/genetics.104.037689
  title: 'Insertion/deletion and nucleotide polymorphism data reveal constraints in <i>Drosophila melanogaster</i> introns and intergenic regions'
  image: images/article_thumbnails/thumb.droso_indels.png

- id: doi:10.1093/genetics/165.3.1269
  title: 'Demography and natural selection have shaped genetic variation in <i>Drosophila melanogaster</i>: A multi-locus approach'
  image: images/article_thumbnails/thumb.droso_glinka.png

- id: doi:10.1006/eesa.2000.2005
  title: 'Teratogenic and toxic effects of Alcohol Ethoxylate and Alcohol Ethoxy Sulfate surfactants on <i>Xenopus laevis</i> embryos and tadpoles'
  image: images/article_thumbnails/thumb.xenopus.png
